### ISSUE TITLE
Complete Milestone 1 Section: Safety and Security Requirements

### ISSUE THREAD

**Issue by soobdoobers42** [Randydom99/INF2001-Project-P9-5#18]

**Comment by CodeXTF2** [comment]
Task title ID: 1.3.3.4.2
What is the task about? 
- Writing security and safety requirements for our ferry planning app
What are the goals of the task? 
- To ensure the client's safety and security needs are met in our app
Success or completion criteria:
- Writing completion
Allocated Time:
- 3 days
Start date and end end date of the issue/task:
- Sept 20 to Sept 23
Who is the owner? 
- Ethan 
Status:  TODO
Priority: Normal

**Comment by CodeXTF2** [comment]
Describe the work done in detail: Created and filled table of security and safety requirements
Has this work been committed to repo: Yes
How does the work affect for success or completion criteria: N/A
Start date and end date of the work done: 20/9/2023 - 23/9/2023
