### ISSUE TITLE
Complete Milestone 1 Section: Performance Requirements

### ISSUE THREAD

**Issue by soobdoobers42** [Randydom99/INF2001-Project-P9-5#19]

**Comment by CodeXTF2** [comment]
Task title ID: 1.3.3.4.1
What is the task about?: List the performance requirements such as data capacity and response times.
What are the goals of the task?: Define the minimum capability of the project to be used to perform its purpose
Success or completion criteria: Requirements written down in planning document
Allocated Time: 1
Start date and end end date of the issue/task: 24/9/2023 - 25/9/2023
Who is the owner? Ethan
The status of the task: Completed
Priority: High

**Comment by CodeXTF2** [comment]
Describe the work done in detail: Documented the requirements for user and ferry capacity, error handling, responsiveness requirements and maintenance processes
Has this work been committed to repo: Yes
How does the work affect for success or completion criteria: No
Start date and end date of the work done:24/9/2023 - 25/9/2023
