### ISSUE TITLE
Complete Milestone 1 Section: Other Requirements

### ISSUE THREAD

**Issue by soobdoobers42** [Randydom99/INF2001-Project-P9-5#26]

**Comment by CodeXTF2** [comment]
Task title ID: 1.3.3.5
What is the task about?
Misc requirements 
What are the goals of the task?
Miscellaneous requirements such as PDPA compliance and backend database implementation
Success or completion criteria:
Writing completion
Allocated Time:
3 days
Start date and end end date of the issue/task:
Sept 23 to Sept 24
Who is the owner?
Ethan
Status: Completed
Priority: Normal

**Comment by CodeXTF2** [comment]
Describe the work done in detail: Created and filled table of of PDPA reqs and MySQL implementation
Has this work been committed to repo: Yes
How does the work affect for success or completion criteria: N/A
Start date and end date of the work done: 23/9/2023 - 25/9/2023
