### ISSUE TITLE
Create use case diagram

### ISSUE THREAD

**Issue by Randydom99** [Randydom99/INF2001-Project-P9-5#3]

**Comment by soobdoobers42** [comment]
Task title ID: 1.5
What is the task about? Designing the Use-Case diagram for the Ferry workload website system that would cover the requirements mentioned by the client
What are the goals of the task? The goal is to design various Use Cases which the system will be using for each of the identified actors
Success or completion criteria: Completion, the requirement has been filled out as detailed as possible, covering all possible use-case scenarios
Allocated Time: 2 - 3 days
Start date and end end date of the issue/task: 21/9/2023 - 23/9/2023
Who is the owner? Michelle Lim (soobdoobers42)
To-Do
Medium Priority

**Comment by soobdoobers42** [comment]
i. Task 1.5 has been designed covering the basis of each identifiable actor: Administrator, Managers, Staff (Crew and Captain) based on how the actors interacts with the system
ii. yes
iii. no
iv. 21/9/2023 - 23/9/2023
