### ISSUE TITLE
M2: Design Sequence Diagram

### ISSUE THREAD

**Issue by soobdoobers42** [Randydom99/INF2001-Project-P9-5#34]
Task title ID: 2.1.3.3.2

What is the task about? To design sequence diagrams which will illustrate the use cases of the project web-application. It would M1 Use Cases.

What are the goals of the task? Design a clear, concise Sequence Diagram.

Success or completion criteria: Have a sequence diagram that is easily understandable and showcasing the proper flow and interaction between each entity/element.

Allocated Time: 1 week

Start date and end end date of the issue/task: 09/10/2023 - 27/10/2023

Who is the owner? Ming Yi

Status: TO-DO

Priority: Medium-High

**Comment by 2201656** [comment]
Has this work been committed to repo: Yes 

How does the work affect for success or completion criteria: Ensuring that the interaction and flow provided in the sequence diagram is proper and understandable.

Start date and end date of the work done: 09/10/2023 - 28/10/2023
