### ISSUE TITLE
M2: Design Class Diagram

### ISSUE THREAD

**Issue by soobdoobers42** [Randydom99/INF2001-Project-P9-5#36]

**Comment by Randydom99** [comment]
Has this work been committed to repo: Yes
How does the work affect for success or completion criteria: Component and Sequence diagram are dependant on the class diagram, changes were made throughout the designing of the class diagram therefore taking additional days to complete.
Start date and end date of the work done: 17/10/2023 - 28/10/2023

**Comment by Randydom99** [comment]
Task title ID: 2.1.3.5.2
What is the task about? To design the class diagram which will provide an overview of the relations between the various entities within the system.
What are the goals of the task? Design a clear, concise Class Diagram according to how was taught in the lecture to show the overall design of the web-application components
Success or completion criteria: When all relationships between all the entities are clearly displayed in the class diagrams through entity, control, boundary and interface classes
Allocated Time: 1-2 days
Start date and end end date of the issue/task: 17/10/2023 - 19/10/2023
Who is the owner? Randy and Ethan
Status: Completed
Priority: High
