### ISSUE TITLE
Complete the M2 report

### ISSUE THREAD

**Issue by soobdoobers42** [Randydom99/INF2001-Project-P9-5#37]
Task title ID: 2.1.3
What is the task about? Complete the entire report, compile all diagrams and updated information into the report.
Success or completion criteria:
Allocated Time: Start of M2 to end of M2
Start date and end end date of the issue/task: 25/9/2023 - 28/10/2023
Who is the owner? All
Status: TO-DO
Priority: High

**Comment by Carment14tham** [comment]
Has this work been committed to repo: Yes
How does the work affect for success or completion criteria: Report is completed including all necessary information and requirements for the submission.
Start date and end date of the work done: 25/9/2023 - 28/10/2023
