### ISSUE TITLE
M3: Design Prototype

### ISSUE THREAD

**Issue by soobdoobers42** [Randydom99/INF2001-Project-P9-5#47]
Task title ID: xxxxxxx

What is the task about? To design a prototype that would showcase our use cases and functional requirements.

What are the goals of the task? Design a clear, concise prototype.

Success or completion criteria: Have a prototype that is easily understandable and showcasing the proper flow.

Allocated Time: x week

Start date and end end date of the issue/task: xx/11/2023 - xx/11/2023

Who is the owner? Ethan, Ming Yi

Status: TO-DO

Priority: Medium-High

**Comment by CodeXTF2** [comment]
Describe the work done in detail: Created prototype in photoshop according to UI requirements and use case diagram
Has this work been committed to repo: Yes
How does the work affect for success or completion criteria: No
Start date and end date of the work done: 20/11/2023-23/11/2023
