### ISSUE TITLE
Complete User Interface Requirements & Functional Requirements

### ISSUE THREAD

**Issue by Randydom99** [Randydom99/INF2001-Project-P9-5#7]
Michelle and Ethan to complete Section 3 of Project Milestone 1

**Comment by soobdoobers42** [comment]
1. Task title ID: 1.3.3.1 & 1.3.3.2
2. What is the task about? Describing the User to System interaction specification of the design, layout and usability of each User Interface Requirements as well as the System Functionality features
3. What are the goals of the task? The goal is to fill out the specification requirement according to the user and functionality requirement with regards to the client's request and meeting notes
4. Success or completion criteria: Completion, the requirement has been filled out as detailed as possible, covering all possible scenarios of user pages and intractability.
5. Allocated Time:  1 - 2 days
6. Start date and end end date of the issue/task: 14/9/2023 - 17/9/2023
7. Who is the owner? Michelle Lim (soobdoobers42)
8. To-Do
9. High Priority

**Comment by soobdoobers42** [comment]
1. Task 1.3.3.1 and 1.3.3.2 has been filled up as a table of requirements. The User Interface Requirements (UIR) has been filled as a list table while the Functional Requirements (FR) table has been filled with separate sections of features for Admin, Managers and Crew Member
2. yes
3. no
4. 14/9/2023 - 17/9/2023
